// Package zones contains the platform's source-of-truth list of supported time zones
package zones

import (
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/michaeldelorenzo/x/v2/pkg/utils/ptr"
	"github.com/michaeldelorenzo/x/v2/pkg/utils/sequence"
)

var ErrUnsupportedTimeZone = errors.New("provided time zone is not supported")

func mustLoadTimeZone(timeZoneIANAName string) string {
	loc, err := time.LoadLocation(timeZoneIANAName)
	if err != nil {
		panic(err)
	}
	return loc.String()
}

// Validate confirms that a time zone is a supported IANA format (case sensitive) time zone
func Validate(zone string) bool {
	return sequence.Contains(supportedTimeZones, zone)
}

// GetSupportedZones returns a list of supported IANA Time Zones
func GetSupportedZones() []string {
	return supportedTimeZones
}

// LoadSupportedZone returns the loaded location for a case insensitive IANA time zone string or an error if it is not found in the supported list
func LoadSupportedZone(zone string) (time.Location, error) {
	loc, ok := supportedLowerCaseZoneMap[strings.ToLower(zone)]
	if !ok {
		return loc, fmt.Errorf("failed to load location for %s: %w", zone, ErrUnsupportedTimeZone)
	}

	return loc, nil
}

// supportedTimeZones contains the list of the platform supported IANA Time Zones
// comprised of only canonical zones specified in https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
var supportedTimeZones = []string{
	mustLoadTimeZone("Africa/Abidjan"),
	mustLoadTimeZone("Africa/Algiers"),
	mustLoadTimeZone("Africa/Bissau"),
	mustLoadTimeZone("Africa/Cairo"),
	mustLoadTimeZone("Africa/Casablanca"),
	mustLoadTimeZone("Africa/Ceuta"),
	mustLoadTimeZone("Africa/El_Aaiun"),
	mustLoadTimeZone("Africa/Johannesburg"),
	mustLoadTimeZone("Africa/Juba"),
	mustLoadTimeZone("Africa/Khartoum"),
	mustLoadTimeZone("Africa/Lagos"),
	mustLoadTimeZone("Africa/Maputo"),
	mustLoadTimeZone("Africa/Monrovia"),
	mustLoadTimeZone("Africa/Nairobi"),
	mustLoadTimeZone("Africa/Ndjamena"),
	mustLoadTimeZone("Africa/Sao_Tome"),
	mustLoadTimeZone("Africa/Tripoli"),
	mustLoadTimeZone("Africa/Tunis"),
	mustLoadTimeZone("Africa/Windhoek"),
	mustLoadTimeZone("America/Adak"),
	mustLoadTimeZone("America/Anchorage"),
	mustLoadTimeZone("America/Araguaina"),
	mustLoadTimeZone("America/Argentina/Buenos_Aires"),
	mustLoadTimeZone("America/Argentina/Catamarca"),
	mustLoadTimeZone("America/Argentina/Cordoba"),
	mustLoadTimeZone("America/Argentina/Jujuy"),
	mustLoadTimeZone("America/Argentina/La_Rioja"),
	mustLoadTimeZone("America/Argentina/Mendoza"),
	mustLoadTimeZone("America/Argentina/Rio_Gallegos"),
	mustLoadTimeZone("America/Argentina/Salta"),
	mustLoadTimeZone("America/Argentina/San_Juan"),
	mustLoadTimeZone("America/Argentina/San_Luis"),
	mustLoadTimeZone("America/Argentina/Tucuman"),
	mustLoadTimeZone("America/Argentina/Ushuaia"),
	mustLoadTimeZone("America/Asuncion"),
	mustLoadTimeZone("America/Bahia"),
	mustLoadTimeZone("America/Bahia_Banderas"),
	mustLoadTimeZone("America/Barbados"),
	mustLoadTimeZone("America/Belem"),
	mustLoadTimeZone("America/Belize"),
	mustLoadTimeZone("America/Boa_Vista"),
	mustLoadTimeZone("America/Bogota"),
	mustLoadTimeZone("America/Boise"),
	mustLoadTimeZone("America/Cambridge_Bay"),
	mustLoadTimeZone("America/Campo_Grande"),
	mustLoadTimeZone("America/Cancun"),
	mustLoadTimeZone("America/Caracas"),
	mustLoadTimeZone("America/Cayenne"),
	mustLoadTimeZone("America/Chicago"),
	mustLoadTimeZone("America/Chihuahua"),
	mustLoadTimeZone("America/Costa_Rica"),
	mustLoadTimeZone("America/Cuiaba"),
	mustLoadTimeZone("America/Danmarkshavn"),
	mustLoadTimeZone("America/Dawson"),
	mustLoadTimeZone("America/Dawson_Creek"),
	mustLoadTimeZone("America/Denver"),
	mustLoadTimeZone("America/Detroit"),
	mustLoadTimeZone("America/Edmonton"),
	mustLoadTimeZone("America/Eirunepe"),
	mustLoadTimeZone("America/El_Salvador"),
	mustLoadTimeZone("America/Fort_Nelson"),
	mustLoadTimeZone("America/Fortaleza"),
	mustLoadTimeZone("America/Glace_Bay"),
	mustLoadTimeZone("America/Goose_Bay"),
	mustLoadTimeZone("America/Grand_Turk"),
	mustLoadTimeZone("America/Guatemala"),
	mustLoadTimeZone("America/Guayaquil"),
	mustLoadTimeZone("America/Guyana"),
	mustLoadTimeZone("America/Halifax"),
	mustLoadTimeZone("America/Havana"),
	mustLoadTimeZone("America/Hermosillo"),
	mustLoadTimeZone("America/Indiana/Indianapolis"),
	mustLoadTimeZone("America/Indiana/Knox"),
	mustLoadTimeZone("America/Indiana/Marengo"),
	mustLoadTimeZone("America/Indiana/Petersburg"),
	mustLoadTimeZone("America/Indiana/Tell_City"),
	mustLoadTimeZone("America/Indiana/Vevay"),
	mustLoadTimeZone("America/Indiana/Vincennes"),
	mustLoadTimeZone("America/Indiana/Winamac"),
	mustLoadTimeZone("America/Inuvik"),
	mustLoadTimeZone("America/Iqaluit"),
	mustLoadTimeZone("America/Jamaica"),
	mustLoadTimeZone("America/Juneau"),
	mustLoadTimeZone("America/Kentucky/Louisville"),
	mustLoadTimeZone("America/Kentucky/Monticello"),
	mustLoadTimeZone("America/La_Paz"),
	mustLoadTimeZone("America/Lima"),
	mustLoadTimeZone("America/Los_Angeles"),
	mustLoadTimeZone("America/Maceio"),
	mustLoadTimeZone("America/Managua"),
	mustLoadTimeZone("America/Manaus"),
	mustLoadTimeZone("America/Martinique"),
	mustLoadTimeZone("America/Matamoros"),
	mustLoadTimeZone("America/Mazatlan"),
	mustLoadTimeZone("America/Menominee"),
	mustLoadTimeZone("America/Merida"),
	mustLoadTimeZone("America/Metlakatla"),
	mustLoadTimeZone("America/Mexico_City"),
	mustLoadTimeZone("America/Miquelon"),
	mustLoadTimeZone("America/Moncton"),
	mustLoadTimeZone("America/Monterrey"),
	mustLoadTimeZone("America/Montevideo"),
	mustLoadTimeZone("America/New_York"),
	mustLoadTimeZone("America/Nome"),
	mustLoadTimeZone("America/Noronha"),
	mustLoadTimeZone("America/North_Dakota/Beulah"),
	mustLoadTimeZone("America/North_Dakota/Center"),
	mustLoadTimeZone("America/North_Dakota/New_Salem"),
	mustLoadTimeZone("America/Nuuk"),
	mustLoadTimeZone("America/Ojinaga"),
	mustLoadTimeZone("America/Panama"),
	mustLoadTimeZone("America/Paramaribo"),
	mustLoadTimeZone("America/Phoenix"),
	mustLoadTimeZone("America/Port-au-Prince"),
	mustLoadTimeZone("America/Porto_Velho"),
	mustLoadTimeZone("America/Puerto_Rico"),
	mustLoadTimeZone("America/Punta_Arenas"),
	mustLoadTimeZone("America/Rankin_Inlet"),
	mustLoadTimeZone("America/Recife"),
	mustLoadTimeZone("America/Regina"),
	mustLoadTimeZone("America/Resolute"),
	mustLoadTimeZone("America/Rio_Branco"),
	mustLoadTimeZone("America/Santarem"),
	mustLoadTimeZone("America/Santiago"),
	mustLoadTimeZone("America/Santo_Domingo"),
	mustLoadTimeZone("America/Sao_Paulo"),
	mustLoadTimeZone("America/Scoresbysund"),
	mustLoadTimeZone("America/Sitka"),
	mustLoadTimeZone("America/St_Johns"),
	mustLoadTimeZone("America/Swift_Current"),
	mustLoadTimeZone("America/Tegucigalpa"),
	mustLoadTimeZone("America/Thule"),
	mustLoadTimeZone("America/Tijuana"),
	mustLoadTimeZone("America/Toronto"),
	mustLoadTimeZone("America/Vancouver"),
	mustLoadTimeZone("America/Whitehorse"),
	mustLoadTimeZone("America/Winnipeg"),
	mustLoadTimeZone("America/Yakutat"),
	mustLoadTimeZone("Asia/Almaty"),
	mustLoadTimeZone("Asia/Amman"),
	mustLoadTimeZone("Asia/Anadyr"),
	mustLoadTimeZone("Asia/Aqtau"),
	mustLoadTimeZone("Asia/Aqtobe"),
	mustLoadTimeZone("Asia/Ashgabat"),
	mustLoadTimeZone("Asia/Atyrau"),
	mustLoadTimeZone("Asia/Baghdad"),
	mustLoadTimeZone("Asia/Baku"),
	mustLoadTimeZone("Asia/Bangkok"),
	mustLoadTimeZone("Asia/Barnaul"),
	mustLoadTimeZone("Asia/Beirut"),
	mustLoadTimeZone("Asia/Bishkek"),
	mustLoadTimeZone("Asia/Chita"),
	mustLoadTimeZone("Asia/Choibalsan"),
	mustLoadTimeZone("Asia/Colombo"),
	mustLoadTimeZone("Asia/Damascus"),
	mustLoadTimeZone("Asia/Dhaka"),
	mustLoadTimeZone("Asia/Dili"),
	mustLoadTimeZone("Asia/Dubai"),
	mustLoadTimeZone("Asia/Dushanbe"),
	mustLoadTimeZone("Asia/Famagusta"),
	mustLoadTimeZone("Asia/Gaza"),
	mustLoadTimeZone("Asia/Hebron"),
	mustLoadTimeZone("Asia/Ho_Chi_Minh"),
	mustLoadTimeZone("Asia/Hong_Kong"),
	mustLoadTimeZone("Asia/Hovd"),
	mustLoadTimeZone("Asia/Irkutsk"),
	mustLoadTimeZone("Asia/Jakarta"),
	mustLoadTimeZone("Asia/Jayapura"),
	mustLoadTimeZone("Asia/Jerusalem"),
	mustLoadTimeZone("Asia/Kabul"),
	mustLoadTimeZone("Asia/Kamchatka"),
	mustLoadTimeZone("Asia/Karachi"),
	mustLoadTimeZone("Asia/Kathmandu"),
	mustLoadTimeZone("Asia/Khandyga"),
	mustLoadTimeZone("Asia/Kolkata"),
	mustLoadTimeZone("Asia/Krasnoyarsk"),
	mustLoadTimeZone("Asia/Kuching"),
	mustLoadTimeZone("Asia/Macau"),
	mustLoadTimeZone("Asia/Magadan"),
	mustLoadTimeZone("Asia/Makassar"),
	mustLoadTimeZone("Asia/Manila"),
	mustLoadTimeZone("Asia/Nicosia"),
	mustLoadTimeZone("Asia/Novokuznetsk"),
	mustLoadTimeZone("Asia/Novosibirsk"),
	mustLoadTimeZone("Asia/Omsk"),
	mustLoadTimeZone("Asia/Oral"),
	mustLoadTimeZone("Asia/Pontianak"),
	mustLoadTimeZone("Asia/Pyongyang"),
	mustLoadTimeZone("Asia/Qatar"),
	mustLoadTimeZone("Asia/Qostanay"),
	mustLoadTimeZone("Asia/Qyzylorda"),
	mustLoadTimeZone("Asia/Riyadh"),
	mustLoadTimeZone("Asia/Sakhalin"),
	mustLoadTimeZone("Asia/Samarkand"),
	mustLoadTimeZone("Asia/Seoul"),
	mustLoadTimeZone("Asia/Shanghai"),
	mustLoadTimeZone("Asia/Singapore"),
	mustLoadTimeZone("Asia/Srednekolymsk"),
	mustLoadTimeZone("Asia/Taipei"),
	mustLoadTimeZone("Asia/Tashkent"),
	mustLoadTimeZone("Asia/Tbilisi"),
	mustLoadTimeZone("Asia/Tehran"),
	mustLoadTimeZone("Asia/Thimphu"),
	mustLoadTimeZone("Asia/Tokyo"),
	mustLoadTimeZone("Asia/Tomsk"),
	mustLoadTimeZone("Asia/Ulaanbaatar"),
	mustLoadTimeZone("Asia/Urumqi"),
	mustLoadTimeZone("Asia/Ust-Nera"),
	mustLoadTimeZone("Asia/Vladivostok"),
	mustLoadTimeZone("Asia/Yakutsk"),
	mustLoadTimeZone("Asia/Yangon"),
	mustLoadTimeZone("Asia/Yekaterinburg"),
	mustLoadTimeZone("Asia/Yerevan"),
	mustLoadTimeZone("Atlantic/Azores"),
	mustLoadTimeZone("Atlantic/Bermuda"),
	mustLoadTimeZone("Atlantic/Canary"),
	mustLoadTimeZone("Atlantic/Cape_Verde"),
	mustLoadTimeZone("Atlantic/Faroe"),
	mustLoadTimeZone("Atlantic/Madeira"),
	mustLoadTimeZone("Atlantic/South_Georgia"),
	mustLoadTimeZone("Atlantic/Stanley"),
	mustLoadTimeZone("Australia/Adelaide"),
	mustLoadTimeZone("Australia/Brisbane"),
	mustLoadTimeZone("Australia/Broken_Hill"),
	mustLoadTimeZone("Australia/Darwin"),
	mustLoadTimeZone("Australia/Eucla"),
	mustLoadTimeZone("Australia/Hobart"),
	mustLoadTimeZone("Australia/Lindeman"),
	mustLoadTimeZone("Australia/Lord_Howe"),
	mustLoadTimeZone("Australia/Melbourne"),
	mustLoadTimeZone("Australia/Perth"),
	mustLoadTimeZone("Australia/Sydney"),
	mustLoadTimeZone("Etc/UTC"),
	mustLoadTimeZone("Europe/Andorra"),
	mustLoadTimeZone("Europe/Astrakhan"),
	mustLoadTimeZone("Europe/Athens"),
	mustLoadTimeZone("Europe/Belgrade"),
	mustLoadTimeZone("Europe/Berlin"),
	mustLoadTimeZone("Europe/Brussels"),
	mustLoadTimeZone("Europe/Bucharest"),
	mustLoadTimeZone("Europe/Budapest"),
	mustLoadTimeZone("Europe/Chisinau"),
	mustLoadTimeZone("Europe/Dublin"),
	mustLoadTimeZone("Europe/Gibraltar"),
	mustLoadTimeZone("Europe/Helsinki"),
	mustLoadTimeZone("Europe/Istanbul"),
	mustLoadTimeZone("Europe/Kaliningrad"),
	mustLoadTimeZone("Europe/Kirov"),
	mustLoadTimeZone("Europe/Lisbon"),
	mustLoadTimeZone("Europe/London"),
	mustLoadTimeZone("Europe/Madrid"),
	mustLoadTimeZone("Europe/Malta"),
	mustLoadTimeZone("Europe/Minsk"),
	mustLoadTimeZone("Europe/Moscow"),
	mustLoadTimeZone("Europe/Paris"),
	mustLoadTimeZone("Europe/Prague"),
	mustLoadTimeZone("Europe/Riga"),
	mustLoadTimeZone("Europe/Rome"),
	mustLoadTimeZone("Europe/Samara"),
	mustLoadTimeZone("Europe/Saratov"),
	mustLoadTimeZone("Europe/Simferopol"),
	mustLoadTimeZone("Europe/Sofia"),
	mustLoadTimeZone("Europe/Tallinn"),
	mustLoadTimeZone("Europe/Tirane"),
	mustLoadTimeZone("Europe/Ulyanovsk"),
	mustLoadTimeZone("Europe/Vienna"),
	mustLoadTimeZone("Europe/Vilnius"),
	mustLoadTimeZone("Europe/Volgograd"),
	mustLoadTimeZone("Europe/Warsaw"),
	mustLoadTimeZone("Europe/Zurich"),
	mustLoadTimeZone("Indian/Chagos"),
	mustLoadTimeZone("Indian/Maldives"),
	mustLoadTimeZone("Indian/Mauritius"),
	mustLoadTimeZone("Pacific/Apia"),
	mustLoadTimeZone("Pacific/Auckland"),
	mustLoadTimeZone("Pacific/Bougainville"),
	mustLoadTimeZone("Pacific/Chatham"),
	mustLoadTimeZone("Pacific/Easter"),
	mustLoadTimeZone("Pacific/Efate"),
	mustLoadTimeZone("Pacific/Fakaofo"),
	mustLoadTimeZone("Pacific/Fiji"),
	mustLoadTimeZone("Pacific/Galapagos"),
	mustLoadTimeZone("Pacific/Gambier"),
	mustLoadTimeZone("Pacific/Guadalcanal"),
	mustLoadTimeZone("Pacific/Guam"),
	mustLoadTimeZone("Pacific/Honolulu"),
	mustLoadTimeZone("Pacific/Kanton"),
	mustLoadTimeZone("Pacific/Kiritimati"),
	mustLoadTimeZone("Pacific/Kosrae"),
	mustLoadTimeZone("Pacific/Kwajalein"),
	mustLoadTimeZone("Pacific/Marquesas"),
	mustLoadTimeZone("Pacific/Nauru"),
	mustLoadTimeZone("Pacific/Niue"),
	mustLoadTimeZone("Pacific/Norfolk"),
	mustLoadTimeZone("Pacific/Noumea"),
	mustLoadTimeZone("Pacific/Pago_Pago"),
	mustLoadTimeZone("Pacific/Palau"),
	mustLoadTimeZone("Pacific/Pitcairn"),
	mustLoadTimeZone("Pacific/Port_Moresby"),
	mustLoadTimeZone("Pacific/Rarotonga"),
	mustLoadTimeZone("Pacific/Tahiti"),
	mustLoadTimeZone("Pacific/Tarawa"),
	mustLoadTimeZone("Pacific/Tongatapu"),
}

// supportedLowerCaseZoneMap contains a mapping of lower-cased time zones to their time.Location struct counterparts
var supportedLowerCaseZoneMap = sequence.Reduce(supportedTimeZones, map[string]time.Location{}, func(acc map[string]time.Location, el string) map[string]time.Location {
	loc, _ := time.LoadLocation(el)
	acc[strings.ToLower(el)] = ptr.Deref(loc)
	return acc
})
